name: Waka Readme Stats

on:

  push:

    branches: [master]

    pull_request:

      branches: [master]

  schedule:

    - cron: '0 0 * * *'

jobs:

  update-readme:

    name: Update Readme with Metrics

    runs-on: ubuntu-latest

    steps:

      - uses: cxyfreedom/waka-readme-stats@master

        with:

          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_PROJECTS: "True"

          SHOW_TIMEZONE: "True"
